"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see:
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv


# ======================================================================
# Base
# ======================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Local .env file.
# On Vercel, environment variables are provided by the platform.
load_dotenv(BASE_DIR / ".env")


# Detect Vercel runtime.
IS_VERCEL = bool(os.getenv("VERCEL"))


# ======================================================================
# Security
# ======================================================================

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-qj$luv*rxy3_jj=of(#mzt71%z670j1!%3@-#n$2o5+=s-4o2m",
)

DEBUG = os.getenv(
    "DEBUG",
    "True",
).lower() == "true"


# ======================================================================
# Allowed Hosts
# ======================================================================

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "localhost,127.0.0.1",
    ).split(",")
    if host.strip()
]


# Allow Vercel-generated deployment/preview domains.
if IS_VERCEL and ".vercel.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".vercel.app")


# ======================================================================
# Gemini
# ======================================================================

GEMINI_API_KEY = os.getenv(
    "GEMINI_API_KEY"
)

if not GEMINI_API_KEY:
    raise ValueError(
        "GEMINI_API_KEY is not set in the environment variables."
    )


# ======================================================================
# Installed Apps
# ======================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "django_q",
    "corsheaders",

    # Project apps
    "doc_process",
]


# ======================================================================
# Middleware
# ======================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # CORS should be before CommonMiddleware.
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ======================================================================
# URLs / WSGI
# ======================================================================

ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"


# ======================================================================
# Templates
# ======================================================================

TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django.DjangoTemplates"
        ),
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                (
                    "django.template.context_processors.request"
                ),
                (
                    "django.contrib.auth."
                    "context_processors.auth"
                ),
                (
                    "django.contrib.messages."
                    "context_processors.messages"
                ),
            ],
        },
    },
]


# ======================================================================
# CORS
# ======================================================================

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        (
            "http://localhost:3000,"
            "http://127.0.0.1:3000,"
            "http://localhost:5173,"
            "http://127.0.0.1:5173"
        ),
    ).split(",")
    if origin.strip()
]


# ======================================================================
# Database
# ======================================================================

DATABASE_URL = os.getenv(
    "DATABASE_URL"
)


# Prevent accidental SQLite usage on Vercel.
#
# Vercel filesystem is not where we want to store application data.
# Production must use PostgreSQL.
if IS_VERCEL and not DATABASE_URL:
    raise ValueError(
        "DATABASE_URL must be configured on Vercel."
    )


if DATABASE_URL:
    # --------------------------------------------------------------
    # Production / Vercel
    # PostgreSQL
    # --------------------------------------------------------------

    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
        )
    }

else:
    # --------------------------------------------------------------
    # Local development
    # Existing SQLite database
    # --------------------------------------------------------------

    DATABASES = {
        "default": {
            "ENGINE": (
                "django.db.backends.sqlite3"
            ),
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {
                "timeout": 30,
                "transaction_mode": "IMMEDIATE",
            },
        }
    }


# ======================================================================
# File Storage Strategy
# ======================================================================
#
# Current project architecture:
#
# LOCAL
# -----
# SQLite
# FileField / filesystem
#
# PRODUCTION / VERCEL
# -------------------
# PostgreSQL
# BinaryField
#
# We derive this automatically from DATABASE_URL so there is no separate
# FILE_STORAGE_BACKEND environment variable to forget on Vercel.
# ======================================================================

FILE_STORAGE_BACKEND = (
    "database"
    if DATABASE_URL
    else "local"
)


# ======================================================================
# Password Validation
# ======================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ======================================================================
# Internationalization
# ======================================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ======================================================================
# Static Files
# ======================================================================

STATIC_URL = "static/"


# ======================================================================
# Default Primary Key
# ======================================================================

DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ======================================================================
# Django-Q2
# ======================================================================
#
# LOCAL:
# python manage.py qcluster
#
# Production does NOT run a persistent qcluster process.
# Production task dispatch is handled separately by the Vercel/Celery
# integration.
# ======================================================================

Q_CLUSTER = {
    "name": "DocProcessor",
    "workers": 1,
    "recycle": 500,
    "timeout": 120,
    "retry": 180,
    "compress": True,
    "save_limit": 250,
    "queue_limit": 100,
    "label": "Django Q",
    "orm": "default",
}


# ======================================================================
# GapGPT API Configuration
# ======================================================================

GAPGPT_API_KEY = os.getenv(
    "GAPGPT_API_KEY",
    "",
)

GAPGPT_BASE_URL = os.getenv(
    "GAPGPT_BASE_URL",
    "https://api.gapgpt.app/v1",
)

GAPGPT_MODEL = os.getenv(
    "GAPGPT_MODEL",
    "gpt-4o-mini",
)

GAPGPT_TIMEOUT = float(
    os.getenv(
        "GAPGPT_TIMEOUT",
        "120",
    )
)

GAPGPT_MAX_RETRIES = int(
    os.getenv(
        "GAPGPT_MAX_RETRIES",
        "3",
    )
)

GAPGPT_TEMPERATURE = float(
    os.getenv(
        "GAPGPT_TEMPERATURE",
        "0.1",
    )
)