[project]
name = "intelligent-book-editor-backend"
version = "0.1.0"
requires-python = ">=3.12,<3.13"

dependencies = [
    "Django==6.0.7",
    "djangorestframework==3.17.1",
    "django-q2==1.10.0",
    "django-picklefield==3.4.0",
    "django-cors-headers",
    "python-dotenv==1.2.2",
    "python-docx==1.2.0",
    "lxml==6.1.1",
    "openai==2.46.0",
    "httpx==0.28.1",
    "pydantic==2.13.4",
    "python-dateutil==2.9.0.post0",

    "dj-database-url",
    "psycopg[binary]",

    "celery"
]

[tool.vercel]
entrypoint = "config.wsgi:application"

[[tool.vercel.subscribers]]
entrypoint = "worker:app"
topics = ["celery"]