# Generated by Django 6.0.7 on 2026-07-15 16:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_file', models.FileField(upload_to='documents/originals/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('reviewing', 'Reviewing'), ('reviewed', 'Reviewed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('table_cell', 'Table Cell')], db_index=True, max_length=20)),
                ('order_index', models.PositiveIntegerField(db_index=True)),
                ('raw_text', models.TextField(blank=True)),
                ('normalized_text', models.TextField(blank=True)),
                ('style_name', models.CharField(blank=True, max_length=120)),
                ('is_rtl', models.BooleanField(default=False)),
                ('alignment', models.CharField(blank=True, max_length=20)),
                ('paragraph_index', models.PositiveIntegerField(blank=True, null=True)),
                ('table_index', models.PositiveIntegerField(blank=True, null=True)),
                ('row_index', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_index', models.PositiveIntegerField(blank=True, null=True)),
                ('cell_paragraph_index', models.PositiveIntegerField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, db_index=True, max_length=255)),
                ('format_metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='doc_process.document')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ReviewJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_jobs', to='doc_process.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='warning', max_length=20)),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('suggestion_text', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='doc_process.document')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='doc_process.documentblock')),
                ('review_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='doc_process.reviewjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='documentblock',
            index=models.Index(fields=['document', 'order_index'], name='doc_process_documen_7a0896_idx'),
        ),
        migrations.AddIndex(
            model_name='documentblock',
            index=models.Index(fields=['document', 'block_type'], name='doc_process_documen_06bec1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentblock',
            index=models.Index(fields=['document', 'source_path'], name='doc_process_documen_0690df_idx'),
        ),
        migrations.AddIndex(
            model_name='blockissue',
            index=models.Index(fields=['document', 'severity'], name='doc_process_documen_849543_idx'),
        ),
        migrations.AddIndex(
            model_name='blockissue',
            index=models.Index(fields=['block', 'start_offset'], name='doc_process_block_i_2c0162_idx'),
        ),
        migrations.AddIndex(
            model_name='blockissue',
            index=models.Index(fields=['review_job'], name='doc_process_review__384cec_idx'),
        ),
    ]
