# Generated by Django 6.0.7 on 2026-07-21 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentblock',
            name='parent_heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_blocks', to='doc_process.documentblock'),
        ),
    ]
