# Generated by Django 6.0.7 on 2026-07-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_process', '0002_documentblock_parent_heading'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentblock',
            index=models.Index(fields=['document', 'parent_heading'], name='doc_process_documen_8b8476_idx'),
        ),
    ]
