# Generated by Django 6.0.7 on 2026-07-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_process', '0003_documentblock_doc_process_documen_8b8476_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentblock',
            name='heading_level',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('table_cell', 'Table Cell')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='documentblock',
            index=models.Index(fields=['document', 'heading_level'], name='doc_process_documen_1d1a86_idx'),
        ),
    ]
