# Generated by Django 6.0.7 on 2026-07-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_process', '0004_documentblock_heading_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockissue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blockissue',
            name='issue_code',
            field=models.CharField(choices=[('spelling', 'Spelling Error'), ('grammar', 'Grammar and Syntax'), ('style', 'Writing Style and Tone'), ('punctuation', 'Punctuation and Spacing'), ('optimization', 'Readability and Optimization')], db_index=True, default='optimization', max_length=100),
        ),
    ]
