# Generated by Django 6.0.7 on 2026-07-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_process', '0005_alter_blockissue_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='exported_docx',
            field=models.FileField(blank=True, null=True, upload_to='documents/exports/'),
        ),
        migrations.AddField(
            model_name='document',
            name='exported_docx_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='exported_docx_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
