# Generated by Django 6.0.7 on 2026-07-28 05:45

import doc_process.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_process', '0006_document_exported_docx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='exported_docx',
            field=models.FileField(blank=True, null=True, upload_to=doc_process.models.get_dynamic_export_path),
        ),
    ]
