# Generated by Django 6.0.7 on 2026-08-01 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_process', '0007_alter_document_exported_docx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difference_type', models.CharField(choices=[('word_change', 'Word Change'), ('whitespace_change', 'Whitespace Change')], db_index=True, max_length=30)),
                ('change_kind', models.CharField(choices=[('replacement', 'Replacement'), ('insertion', 'Insertion'), ('deletion', 'Deletion'), ('word_and_whitespace_change', 'Word and Whitespace Change'), ('space_to_half_space', 'Space to Half-space'), ('half_space_to_space', 'Half-space to Space'), ('extra_whitespace_removed', 'Extra Whitespace Removed'), ('whitespace_inserted', 'Whitespace Inserted'), ('whitespace_replaced', 'Whitespace Replaced')], db_index=True, max_length=50)),
                ('raw_phrase', models.TextField(blank=True)),
                ('normalized_phrase', models.TextField(blank=True)),
                ('raw_start_offset', models.PositiveIntegerField()),
                ('raw_end_offset', models.PositiveIntegerField()),
                ('normalized_start_offset', models.PositiveIntegerField()),
                ('normalized_end_offset', models.PositiveIntegerField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differences', to='doc_process.documentblock')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differences', to='doc_process.document')),
                ('review_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='differences', to='doc_process.reviewjob')),
            ],
            options={
                'ordering': ['raw_start_offset', 'id'],
                'indexes': [models.Index(fields=['document', 'block', 'raw_start_offset'], name='doc_process_documen_0dc6c8_idx'), models.Index(fields=['block', 'difference_type'], name='doc_process_block_i_bc05a9_idx'), models.Index(fields=['block', 'change_kind'], name='doc_process_block_i_484138_idx'), models.Index(fields=['review_job'], name='doc_process_review__b39d5a_idx')],
            },
        ),
    ]
