# Generated by Django 6.0.7 on 2026-08-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_process', '0008_blockdifference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('docx', 'DOCX'), ('raw_text', 'Raw text')], db_index=True, default='docx', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/originals/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('reviewing', 'Reviewing'), ('reviewed', 'Reviewed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'source_type'], name='doc_process_status_615154_idx'),
        ),
    ]
