# Generated by Django 6.0.7 on 2026-08-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_process', '0009_alter_document_options_document_raw_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('reviewing', 'Reviewing'), ('reviewed', 'Reviewed'), ('ai_reviewing', 'AI Reviewing'), ('ai_reviewed', 'AI Reviewed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20),
        ),
    ]
